31-01-2024:14:45:41,813 INFO     [attempts.py:6] Retrying <function retry_function at 0x101bbaa20>: attempt 1 ended with: <Future at 0x1014aa0c0 state=finished raised Exception>
31-01-2024:14:45:42,819 INFO     [attempts.py:6] Retrying <function retry_function at 0x101bbaa20>: attempt 2 ended with: <Future at 0x1014aa0c0 state=finished raised Exception>
31-01-2024:14:45:44,822 INFO     [attempts.py:6] Retrying <function retry_function at 0x101bbaa20>: attempt 3 ended with: <Future at 0x1014aa0c0 state=finished raised Exception>
31-01-2024:14:45:47,824 INFO     [attempts.py:6] Retrying <function retry_function at 0x101bbaa20>: attempt 4 ended with: <Future at 0x1014aa0c0 state=finished raised Exception>
